apiVersion: v1
kind: ConfigMap
metadata:
  name: fourier-endpoints-config
  namespace: sre
data:
  endpoints.json: |
    {
      "rabbitmq": {
        "TARGET_QUERY": "sum(rabbitmq_queue_messages_ready{self=\"1\"})",
        "REGRESSOR_RATE": "sum(rate(rabbitmq_queue_messages_published_total{self=\"1\"}[5m])) / clamp_min(sum(rate(rabbitmq_queue_messages_ack_total{self=\"1\"}[5m])), 1)"
      }
    }