apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rmqdetector-monitor
  namespace: sre
  labels:
    app: rmqdetector
spec:
  selector:
    matchLabels:
      app: rmqdetector
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1m  # Scrape every 1 minute
      scrapeTimeout: 30s