apiVersion: v1
kind: Service
metadata:
  name: rmqdetector
  namespace: sre
  labels:
    app: rmqdetector
spec:
  selector:
    app: rmqdetector
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: metrics