apiVersion: v1
kind: Service
metadata:
  name: fourier-anomaly-detector
  namespace: sre
  labels:
    app: fourier-anomaly-detector
spec:
  selector:
    app: fourier-anomaly-detector
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: metrics